alias ll='ls -lahoF'
alias la='ls -A'
alias l='ls -CF'
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias mplayer='mplayer -nojoystick -nolirc '
alias ncmpc='ncmpc --colors'
